config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "events#index"

  resources :events
  namespace :admin do
    root "events#index"
    resources :events
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find params[:id]
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new event_params
    if @event.save
      redirect_to admin_events_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find params[:id]
  end

  def update
    @event = Event.find params[:id]
    if @event.update(event_params)
      redirect_to admin_events_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find params[:id]
    @event.destroy

    redirect_to admin_events_path
  end

  protected
  def event_params
    params.require(:event).permit(:name, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find params[:id]
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@event.errors.count, "error") %> prohibited this person from being saved:</h2>

    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, :class => "form-control" %>
</div>

app/views/admin/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_for [:admin, @event] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "Update", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_events_path %>
  </div>
<% end %>

app/views/admin/events/index.html.erb
<h1>Admin Event List</h1>

<p class="text-right">
<%= link_to "New Event", new_admin_event_path, :class => "btn btn-primary" %>
</p>

<table class="table">
<tr>
  <th>Event Name</th>
  <th>Actions</th>
</tr>
<% @events.each do |event| %>
  <tr>
    <td><%= link_to event.name, admin_event_path(event) %></td>
    <td>
      <%= link_to "Edit", edit_admin_event_path(event), :class => "btn btn-default" %>
      <%= link_to "Delete", admin_event_path(event), data: {  turbo_method: :delete, turbo_confirm: "Are you sure?" }, :class => "btn btn-danger" %>
  </tr>
<% end %>
</table>

app/views/admin/events/new.html.erb
<h1>New Event</h1>

<%= form_for [:admin, @event] do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "Create", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_events_path %>
  </div>
<% end %>

app/views/admin/events/show.html.erb
<h1><%= @event.name %></h1>

<p>
  <%= link_to "打开前台", event_path(@event), :target => "_blank", :class => "btn btn-primary" %>
</p>

<%= simple_format @event.description %>

app/views/events/index.html.erb
<h1>Event List</h1>

<ul>
  <% @events.each do |event| %>
    <li>
      <%= link_to event.name, event %>
    </li>
  <% end %>
</ul>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<%= simple_format @event.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsEventList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>